version: '3.1'

services:
  mysql-product-service-db:
    container_name: mysql-product-service-ac # ac means azericard
    image: mysql:8.0
    restart: always
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
