version: '3.1'

services:
  mysql-user-service-db:
    container_name: mysql-user-service-ac # ac means azericard
    image: mysql:8.0
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root